import { useState } from "react";

function ResponseCard({ response, darkMode }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    if (!response) return;

    await navigator.clipboard.writeText(response);
    setCopied(true);

    setTimeout(() => {
      setCopied(false);
    }, 1500);
  };

  if (!response) {
    return (
      <div
        className={`h-full min-h-[560px] rounded-3xl border flex flex-col items-center justify-center text-center p-8 ${
          darkMode
            ? "bg-gray-900 border-gray-800 text-gray-300"
            : "bg-[#0f1524] border-slate-800 text-gray-300"
        }`}
      >
        <div className="text-5xl mb-6">💡</div>

        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-indigo-950 border border-indigo-700 text-indigo-300 text-sm mb-6">
          <span className="w-2 h-2 rounded-full bg-green-400" />
          Ready
        </div>

        <h2 className="text-2xl font-bold text-white mb-3">
          Ready to Analyze
        </h2>

        <p className="max-w-md leading-7 text-gray-400">
          Submit a coding question, error, or problem from the left panel.
          Your AI-generated analysis will appear here.
        </p>
      </div>
    );
  }

  return (
    <div
      className={`h-full min-h-[560px] rounded-3xl border overflow-hidden ${
        darkMode
          ? "bg-gray-900 border-gray-800"
          : "bg-[#0f1524] border-slate-800"
      }`}
    >
      {/* Response Header */}
      <div className="flex items-center justify-between px-6 py-5 border-b border-slate-800">
        <div>
          <div className="flex items-center gap-3">
            <span className="w-2.5 h-2.5 rounded-full bg-green-400" />

            <h2 className="text-xl font-bold text-white">
              AI Response
            </h2>
          </div>

          <p className="text-sm text-gray-400 mt-1">
            Generated by Gemini AI
          </p>
        </div>

        <button
          onClick={handleCopy}
          className="px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-medium transition"
        >
          {copied ? "Copied!" : "Copy"}
        </button>
      </div>

      {/* Actual AI Output */}
      <div className="p-6">
        <div
          className={`min-h-[430px] max-h-[560px] overflow-y-auto rounded-2xl border p-6 ${
            darkMode
              ? "bg-black/40 border-gray-800"
              : "bg-[#080c16] border-slate-800"
          }`}
        >
          <pre className="whitespace-pre-wrap break-words font-sans text-[15px] leading-7 text-gray-200">
            {response}
          </pre>
        </div>
      </div>
    </div>
  );
}

export default ResponseCard;
